version: '3.9'
services:
  nginx-rtmp:
    #image: tiangolo/nginx-rtmp:latest
    image: nginx-rtmp:latest
    container_name: nginx-rtmp
    restart: always
    ports:
      - 1935:1935
      - 1980:80
  web:
    build: .
    container_name: nginx-fstv
    ports:
      - 9991:9991
    networks:
      - default
    volumes:
      - data:/data

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
